import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import signin from "@/app/(auth)/sign-in/[[...sign-in]]/page";
import signup from "@/app/(auth)/sign-up/[[...sign-up]]/page";

import { QueryProviders } from "@/provider/queryProvider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { NewAccountSheet } from "@/features/accounts/api/components/new-account-sheet";
import { SheetProvider } from "@/provider/sheetProvider";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
    <ClerkProvider>
       <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
        <QueryProviders>
          <SheetProvider />
          <Toaster />
          {children}
        </QueryProviders>
        
          
        </header>
        {/* {children} */}
      </body>
    </html>
    </ClerkProvider>
  );
}
